name: "Test Nodejs App"
description: "Test a Nodejs application (frontend)"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: create env file
      shell: bash
      run: |
        touch .env
        echo VITE_MAPBOX=${{ secrets.VITE_MAPBOX }} >> .env

    - name: Run unit tests
      shell: bash
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: |
        npm ci
        npm run test:all
