name: "Test Coverage Nodejs App"
description: "Test Coverage for a Nodejs application (frontend)"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Coverage
      shell: bash
      run: |
        npm ci
        npm run coverage
    - name: Report Coverage
      if: always()
      uses: davelosert/vitest-coverage-report-action@v1
