name: "Test Coverage Nodejs App"
description: "Test Coverage for a Nodejs application (frontend)"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: ArtiomTr/jest-coverage-report-action@v2
      id: coverage
      with:
        output: report-markdown
        test-script: npm test -- --coverage
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: ${{ steps.coverage.outputs.report }}
