name: "Build Nodejs App"
description: "Build a Nodejs application (frontend)"

runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Run build
      shell: bash
      env:
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: |
        npm ci
        npm run build --if-present
